### ISSUE TITLE
Incorrect yaml configuration creation for neo4j-reverse-proxy

### ISSUE THREAD

**Issue by kostorub** [neo4j/docs-operations#1185]
Hello!

I followed this [Manual](https://neo4j.com/docs/operations-manual/current/kubernetes/accessing-neo4j-ingress)
I generated a TLS certificate by certbot for godaddy domain name.
I added it to the kubernetes secret.
Created the following ingress-values.yaml
```
reverseProxy:
  image: neo4j/helm-charts-reverse-proxy:5.12.0
  serviceName: "neo4j-lb"
  ingress:
    enabled: true
    tls:
      enabled: true
      config:
      - secretName: "mydomain-tls" <--- set the secret
        hosts:
          - mydomain.com <--- set the domain name
 ```
After step [Install the Reverse proxy Helm chart](https://neo4j.com/docs/operations-manual/current/kubernetes/accessing-neo4j-ingress/#_configure_the_ingress_values_yaml_file_to_access_neo4j_on_port_443) the rp-reverseproxy-ingress.yaml was generated and deployed. Here is the part of that yaml:
```
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: rp-reverseproxy-service
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - mydomain.com
    secretName: mydomain-tls

```
But it will not work. Here is the right yaml piece of configuration:
```
spec:
  ingressClassName: nginx
  rules:
  - host: mydomain.com <--- added this key
    http:
      paths:
      - backend:
          service:
            name: rp-reverseproxy-service
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - mydomain.com
    secretName: mydomain-tls
```
I'n not sure, where should I go?
